# Backup script generated by Areca v7.5 on May 5, 2016 3:31 PM

# Differential backup
# Target Group : "General Backup"
"/opt/areca/bin/areca_cl.sh" backup -d -c -wdir "/tmp/tmp-aaron" -config "/home/aaron/.areca/workspace/General Backup"

