# General
alias kz="kustomize"
alias zshrc="nvim ~/.zshrc;source ~/.zshrc"
alias aliasconf="nvim ~/.bash_aliases;source ~/.bash_aliases"
alias vconf="cd ~/.config/nvim;nvim ~/.config/nvim/init.vim"
alias i3conf="nvim ~/.config/i3/config"
alias ali="nvim ~/.bash_aliases; source ~/.bash_aliases"
alias please=sudo
alias c="xclip -selection clipboard"
alias sctl="sudo systemctl"
alias v="nvim"
alias la="exa -lah"
alias o="xdg-open"
alias tt="taskwarrior-tui"
alias weather='curl "wttr.in?0Fq"'
alias moon="curl wttr.in/moon"
alias record="ffmpeg -f x11grab  -s 1920x1080 -i :0.0 -r 25 -vcodec libx264  output.mkv"

# go
alias gk=ginkgo

# taskwarrior
alias tt="taskwarrior-tui"

# Pacman
alias pS="sudo pacman -S"
alias pSu="sudo pacman -Syu"
alias pSs="pacman -Ss"

# docker
alias dc=docker-compose
alias pc=podman-compose

# Kubernetes
alias k=kubectl
alias kctx=kubectx
alias kns=kubens
alias kc="kubie ctx"
alias kn="kubie ns"
alias knip="kubectl get nodes -o jsonpath='{.items[*].status.addresses[?(@.type==\"InternalIP\")].address}'"
alias kip="kubectl get nodes -o jsonpath='{.items[*].status.addresses[?(@.type==\"ExternalIP\")].address}'"
alias kp="kubectl port-forward --address 0.0.0.0"
alias klo="kubectl logs -f"
alias ke="kubectl exec -ti"
alias kaf="kubectl apply -f"

# alias po for k get po, deploy for k get deploy etc
for res in po deploy svc netsvc slicegw slice ing vs gw dr ds se svcim svcex cm secret serviceexport serviceimport
do
  alias $res="kubectl get $res"
  alias d$res="kubectl describe $res"
  alias e$res="kubectl edit $res"
  alias w$res="watch kubectl get $res"
done

# exec into pod
function ksh(){
  pod=$1
  container=$2
  if [ -z $container ]
  then
    kubectl exec -ti $pod -- sh
  else
    kubectl exec -it $pod -c $container -- sh
  fi
}

# taskwarrior
alias in="task folder:in"
