export ZSH="/home/jayadeep/.oh-my-zsh"
ZSH_THEME=""

plugins=(
	git
	docker
	zsh-syntax-highlighting
	kubectl
)


source $ZSH/oh-my-zsh.sh

# .zshrc
autoload -U promptinit; promptinit
prompt pure


export EDITOR='vim'

export PATH="$PATH:$HOME/.npm-global/bin"
export PATH="$PATH:$HOME/workspace/scripts"
export PATH="$PATH:/opt/lampp/bin:/opt/lampp"
#source virtualenvwrapper.sh
eval $(systemctl --user show-environment | grep SSH_AUTH_SOCK)
export SSH_AUTH_SOCK

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="$HOME/scripts/bin:$PATH"
alias zshrc="vim ~/.zshrc;source ~/.zshrc"
alias please=sudo
alias c="xclip -selection clipboard"
alias v="nvim"
alias pS="sudo pacman -S"
alias pSu="sudo pacman -Syu"
alias pSs="pacman -Ss"
alias sctl="sudo systemctl"
alias o="xdg-open"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source /usr/share/nvm/init-nvm.sh

source /opt/kube-ps1/kube-ps1.sh
PROMPT='$(kube_ps1)'$PROMPT
stty -ixon
