export ZSH="/home/jayadeep/.oh-my-zsh"
fpath+=("$HOME/.zsh/pure")
ZSH_THEME=""

plugins=(
	git
	docker
	zsh-syntax-highlighting
  zsh-nvm
  z
)


source $ZSH/oh-my-zsh.sh

# .zshrc
autoload -U promptinit; promptinit
prompt pure


export EDITOR='vim'

PATH="$HOME/.node/bin:$PATH"
NODE_PATH="$HOME/.node/lib/node_modules:$NODE_PATH"
# export PATH="$PATH:/opt/lampp/bin:/opt/lampp"
#source virtualenvwrapper.sh
eval $(systemctl --user show-environment | grep SSH_AUTH_SOCK)
export SSH_AUTH_SOCK

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
export PATH="$HOME/scripts/bin:$PATH"
export PATH="$PATH:$HOME/workspace/scripts"
alias zshrc="vim ~/.zshrc;source ~/.zshrc"
alias please=sudo
alias c="xclip -selection clipboard"
alias v="nvim"
alias pS="sudo pacman -S"
alias pSu="sudo pacman -Syu"
alias pSs="pacman -Ss"
alias sctl="sudo systemctl"
alias k=kubectl
alias la="exa -lah"

alias brokeradmin='k get ing -o=custom-columns="host:.spec.rules[0].host"  | grep admin-enroll-review-$(git rev-parse --abbrev-ref HEAD  | cut -c 1-7)'


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

